# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!


target 'NoteApp' do
	pod 'Firebase'
	pod 'Firebase/Core'
    pod 'Firebase/AdMob'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks

  # Pods for NoteApp

end
